version: '2'
services:
  fuseki:
    image: toop_sms_fuseki
    build:
      context: ./fuseki/

      args:
        #set trace enabled to 'true' to enable Fuseki TRACE logging, emtpy "" if default logging.
        TRACE_ENABLED: ""
        #set inference enabled to 'true' to enable Pizza Inference, empty "" for no inference. Notice that enabling reasoning might slow down SPARQL queries considerably.
        INFERENCE_ENABLED: ""
        no_proxy: ${env_no_proxy}
        http_proxy: ${env_http_proxy}
        https_proxy: ${env_https_proxy}
    # extra_hosts:
    #   - "fuseki:127.0.0.1"
    ports:
      - "${FUSEKI_PORT}:3030"
    mem_limit: 4000m
    environment:
      no_proxy: ${env_no_proxy}
      http_proxy: ${env_http_proxy}
      https_proxy: ${env_https_proxy}
      ADMIN_PASSWORD: admin
      JVM_ARGS: -Xmx3500M  
  grlc:
    image: toop_sms_grlc
    build:
      context: ./grlc/
      args:
        no_proxy: ${env_no_proxy}
        http_proxy: ${env_http_proxy}
        https_proxy: ${env_https_proxy}
#    image: clariah/grlc:latest
    restart: unless-stopped
    ports:
     - "${GRLC_PORT}:80"
    environment:
     - no_proxy=${env_no_proxy}
     - http_proxy=${env_http_proxy}
     - https_proxy=${env_https_proxy}
     - DEBUG=true
     - USERMAP_GID=1000
     - USERMAP_UID=1000
     - GRLC_GITHUB_ACCESS_TOKEN= ${env_github_access_token}
     - GRLC_PORT
     - FUSEKI_PORT
     - GRLC_URL
